# Preferences for the Jumper game. You can edit these values to adjust the palying experience

WIDTH: int = 750
HEIGHT: int = 500
TOPLEFT_X: int = 50
TOPLEFT_Y: int = HEIGHT - 100
PLAYER_SIZE: int = 60
PLAYER_ASSETS: list = ["assets/3.png", "assets/4.png"]
ENEMY_ASSETS: list = ["assets/1.png", "assets/6.png"]
PARTICLE_ASSETS: list = ["assets/star0.png"]
ENEMY_SIZE: int = 25
BOOST: int = -15
SPEED: float = -5
GRAVITY: int = 1
GAP: float = 200
ANIM_DELAY: float = 0.1
ENEMY_CHANCE: int = 10
MAX_ENEMY_HEIGHT: int = PLAYER_SIZE * 2
PARTICLE_CHANCE: int = 3
MAX_ENEMIES: int = 5
MIN_FPS: float = 100
MAX_FPS: float = 200
FPS_INCREASE: float = 0.5
JUMP_KEY: list = ["<space>", "<Up>", "<Button-1>"]
PAUSE_KEY: list = ["<Escape>", "<p>", "<Button-3>"]
SCOREBOARD = "jumper.scores"
MID_Y: float = HEIGHT / 2
MID_X: float = WIDTH / 2
GROUND: int = round(TOPLEFT_Y + (PLAYER_SIZE / 2))
